[package]
name = "crain"
version = "0.1.0"
edition = "2024"
authors = ["BaiChuanByte <baichuanbyte@outlook.com>"]

description = "A Brainfuck compiler/interpreter/tool"

documentation = "https://docs.rs/crain"
repository = "https://crates.io/crates/crain"
readme = "README.md"

keywords = ["brainfuck", "esolang", "compiler", "interpreter"]
categories = ["compilers", "parser-implementations"]

license = "MIT"

exclude = [
    "CHANGELOG.md",
    "Cargo.lock",
    "LICENSE",
    "LICENSE-WTFPL",
    "NOTICE",
    "README.md",
    "example",
    "rustfmt.toml",
    "target",
]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"
